# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: windows-latest


steps:
#- script: |
#    echo "Current Directory: $(System.DefaultWorkingDirectory)"
#  displayName: 'Print Current Directory'

- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    version: '2.1.x'
  displayName: 'Install .NET SDK'

- script: |
    "C:\BuildAgent\AzureDevOpsAgent\agent\tools\Unity 2022.3.11f1\Editor\Unity.exe" -batchmode -nographics -projectPath "$(System.DefaultWorkingDirectory)\BubbleBlastOnline" -executeMethod BuildTheGame.Build
  displayName: 'Unity Build'


