# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest


steps:
- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    version: '2.1.x'
  displayName: 'Install .NET SDK'

- script: "'C:/BuildAgent/AzureDevOpsAgent/agent/tools/Unity 2022.3.11f1/Editor/Unity.exe' -batchmode -nographics -projectPath 'C:/Users/frede/Desktop/8.StoreSystemerEksamen/BBOnline/BubbleBlastOnline' -executeMethod BuildGame.Build"
  displayName: 'Unity'

